import { notFound } from 'next/navigation';
import { ArrowDownTrayIcon, ArrowRightIcon, CheckBadgeIcon, ClockIcon, SignalIcon, FolderOpenIcon, BriefcaseIcon } from '@heroicons/react/24/outline';
import Breadcrumbs from '@/components/Breadcrumbs';
import TrackCard from '@/components/TrackCard';
import { getTrack, getSchool, tracks, skillCatalog } from '@/lib/academy';

export function generateStaticParams(){return tracks.map(track=>({slug:track.slug}))}
export function generateMetadata({params}){const track=getTrack(params.slug);return{title:track?`${track.name} — Tabflux`:'Role'}}

export default function RolePage({params}) {
  const track=getTrack(params.slug);
  if(!track) notFound();
  const school=getSchool(track.school);
  const related=tracks.filter(item=>item.school===track.school&&item.slug!==track.slug).slice(0,2);
  const facts=[[ClockIcon,'Duration',track.duration],[SignalIcon,'Difficulty',track.difficulty],[FolderOpenIcon,'Projects',track.projects],[BriefcaseIcon,'Outcome',track.roles[0]]];

  return <main>
    <section className="relative overflow-hidden border-b bg-white"><div className="absolute right-0 top-0 h-full w-2/5 surface-grid opacity-30 [mask-image:linear-gradient(to_left,black,transparent)]"/><div className="shell relative py-16 sm:py-24"><Breadcrumbs items={[{label:'Schools',href:'/schools'},{label:school.shortName,href:`/schools/${school.slug}`},{label:track.name}]}/><div className="grid gap-12 lg:grid-cols-[1fr_320px] lg:items-end"><div><span className="rounded-full bg-lilac px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-wider text-violet-700">Career role</span><h1 className="mt-7 max-w-4xl font-display text-6xl leading-[.9] tracking-[-.045em] sm:text-8xl lg:text-[96px]">{track.name}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-zinc-600">{track.summary}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a className="button-primary" href="#enroll">Enroll in Career Track <ArrowRightIcon className="size-4"/></a><a className="button-secondary" href="#roadmap">Download Roadmap <ArrowDownTrayIcon className="size-4"/></a></div></div><div className="rounded-2xl border bg-paper p-6"><p className="eyebrow">Career opportunities</p><div className="mt-5 space-y-3">{track.roles.map(role=><div className="flex items-center gap-3 rounded-xl bg-white p-3 text-sm font-bold" key={role}><span className="size-2 rounded-full bg-success"/>{role}</div>)}</div></div></div></div></section>

    <section className="shell -mt-px"><div className="grid border-x border-b bg-white sm:grid-cols-2 lg:grid-cols-4">{facts.map(([Icon,label,value])=><div className="flex items-center gap-4 border-b p-5 last:border-b-0 sm:border-r lg:border-b-0" key={label}><span className="grid size-10 place-items-center rounded-xl bg-paper text-zinc-500"><Icon className="size-5"/></span><div><span className="text-[9px] font-extrabold uppercase tracking-wider text-zinc-400">{label}</span><strong className="block text-sm">{value}</strong></div></div>)}</div></section>

    <section className="section shell" id="roadmap"><div className="grid gap-12 lg:grid-cols-[.55fr_1.45fr]"><div><p className="eyebrow">Learning roadmap</p><h2 className="mt-6 font-display text-5xl sm:text-6xl">One skill<br/>builds on the next.</h2><p className="mt-6 max-w-sm text-sm leading-7 text-zinc-600">No syllabus overload. Just a clear sequence toward the role.</p></div><div className="relative"><div className="absolute bottom-12 left-[27px] top-8 w-px bg-line"/>{track.skills.map((slug,index)=>{const skill=skillCatalog[slug];return <article className="relative mb-4 grid gap-5 rounded-2xl border bg-white p-6 transition hover:border-zinc-300 hover:shadow-card sm:grid-cols-[48px_1fr_auto] sm:items-center" key={slug}><span className={`z-10 grid size-10 place-items-center rounded-full text-[10px] font-bold ${index===0?'bg-cobalt text-white':'border bg-paper'}`}>0{index+1}</span><div><p className="eyebrow">Skill Course</p><h3 className="mt-2 font-display text-3xl">{skill[0]}</h3><p className="mt-2 text-xs leading-5 text-zinc-500">{skill[1]}</p></div><a href={`/skill-courses/${slug}`} className="button-secondary min-h-10 px-4 text-xs">View course</a></article>})}<div className="relative grid gap-5 rounded-2xl bg-night p-6 text-white sm:grid-cols-[48px_1fr_auto] sm:items-center"><span className="z-10 grid size-10 place-items-center rounded-full bg-success"><CheckBadgeIcon className="size-5"/></span><div><p className="eyebrow !text-zinc-500">Final milestone</p><h3 className="mt-2 font-display text-3xl">Projects + certification</h3><p className="mt-2 text-xs text-zinc-400">Complete {track.projects} reviewed projects and earn your role credential.</p></div><span className="rounded-full bg-white/10 px-3 py-2 text-[10px] font-bold text-blue-200">CAREER READY</span></div></div></div></section>

    <section className="section border-y bg-[#F0F0EC]"><div className="shell"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Portfolio evidence</p><h2 className="mt-6 font-display text-5xl sm:text-6xl">Build. Review. Prove.</h2></div><p className="max-w-md text-sm leading-7 text-zinc-600">Three project formats develop confidence before your capstone.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[['01','Guided build','Learn the professional workflow.','bg-lilac text-violet-700'],['02','Industry simulation','Work through realistic constraints.','bg-sage text-success'],['03','Career capstone','Ship your strongest portfolio proof.','bg-sand text-warning']].map(([n,title,copy,tone])=><article className="card p-7" key={title}><span className={`inline-flex rounded-lg px-3 py-2 text-[10px] font-extrabold ${tone}`}>PROJECT {n}</span><h3 className="mt-12 font-display text-4xl">{title}</h3><p className="mt-4 text-sm leading-6 text-zinc-500">{copy}</p></article>)}</div></div></section>

    <section className="section shell"><div className="grid gap-14 lg:grid-cols-2"><div><p className="eyebrow">Certification</p><div className="mt-7 flex items-center gap-6 rounded-2xl border bg-blue-50 p-7"><span className="grid size-20 shrink-0 place-items-center rounded-full border border-cobalt font-display text-4xl italic text-cobalt">T</span><div><h2 className="font-display text-3xl">{track.name}</h2><p className="mt-2 text-xs text-zinc-500">Verified · Shareable · Project-backed</p></div></div></div><div><p className="eyebrow">Related roles</p><div className="mt-7 grid gap-5 sm:grid-cols-2">{related.map(item=><TrackCard track={item} key={item.slug}/>)}</div></div></div></section>

    <section className="section shell pt-0" id="enroll"><div className="flex flex-col justify-between gap-10 rounded-[28px] bg-cobalt p-9 text-white sm:p-14 lg:flex-row lg:items-center"><div><p className="eyebrow !text-blue-200">Ready when you are</p><h2 className="mt-5 font-display text-5xl sm:text-6xl">Become a {track.name}.</h2><p className="mt-4 text-sm text-blue-100">{track.duration} · {track.projects} portfolio projects · Role certification</p></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><button className="button-secondary min-w-56">Enroll in Career Track</button><button className="min-h-12 rounded-xl border border-white/30 px-6 text-sm font-bold transition hover:bg-white/10">Download Roadmap</button></div></div></section>
  </main>;
}
