import { ArrowRightIcon, CheckIcon } from '@heroicons/react/24/outline';
import AcademyIcon from '@/components/AcademyIcon';
import CareerPathVisual from '@/components/CareerPathVisual';
import SectionHeading from '@/components/SectionHeading';
import TrackCard from '@/components/TrackCard';
import { schools, tracks } from '@/lib/academy';

const featured = ['ai-full-stack-engineer','ai-automation-engineer','ai-career-accelerator'].map(slug=>tracks.find(track=>track.slug===slug));
const schoolVisual = [
  { icon:'engineering', tone:'bg-lilac text-violet-700', stat:'6 roles' },
  { icon:'automation', tone:'bg-sage text-success', stat:'4 roles' },
  { icon:'productivity', tone:'bg-sand text-warning', stat:'4 roles' },
];

export default function Home() {
  return <main>
    <section className="relative overflow-hidden border-b bg-white">
      <div className="absolute inset-0 surface-grid opacity-30 [mask-image:linear-gradient(to_bottom,black,transparent_85%)]"/>
      <div className="shell relative grid min-h-[720px] items-center gap-16 py-20 lg:grid-cols-[1.08fr_.92fr] lg:py-24">
        <div><p className="eyebrow flex items-center gap-3"><span className="size-2 rounded-full bg-cobalt"/>A modern career academy</p><h1 className="mt-8 max-w-3xl font-display text-[62px] font-normal leading-[.88] tracking-[-.055em] sm:text-[88px] lg:text-[104px]">Choose a career.<br/><em className="font-normal text-cobalt">Follow one path.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-zinc-600">Role-based learning that connects every skill, project, and credential to the work you want to do.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a className="button-primary" href="/schools">Explore Tracks <ArrowRightIcon className="size-4"/></a><a className="button-secondary" href="#how-it-works">See how it works</a></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-xs font-semibold text-zinc-500">{['Beginner-friendly paths','Project-based learning','Verified outcomes'].map(item=><span className="flex items-center gap-2" key={item}><CheckIcon className="size-4 text-success"/>{item}</span>)}</div></div>
        <CareerPathVisual/>
      </div>
    </section>

    <section className="section shell" id="how-it-works">
      <div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><p className="eyebrow">A clearer model</p><h2 className="display mt-7 text-5xl sm:text-7xl">No course<br/>guesswork.</h2><p className="mt-6 max-w-md text-base leading-7 text-zinc-600">Start with the role. We organize everything else.</p></div><div className="grid gap-3 sm:grid-cols-3">{[['01','Choose a School','Find your field.'],['02','Select a role','See the full roadmap.'],['03','Build proof','Graduate career-ready.']].map(([n,title,copy],index)=><div className={`rounded-2xl border p-6 ${index===1?'bg-night text-white':'bg-white'}`} key={title}><span className={`text-[10px] font-extrabold ${index===1?'text-blue-300':'text-cobalt'}`}>{n}</span><h3 className="mt-12 font-display text-3xl">{title}</h3><p className={`mt-3 text-xs ${index===1?'text-zinc-400':'text-zinc-500'}`}>{copy}</p></div>)}</div></div>
    </section>

    <section className="section border-y bg-[#F0F0EC]"><div className="shell"><SectionHeading number="01" label="The academy" title={<>Three Schools.<br/>Three directions.</>} copy="Choose the field that matches how you want to work. Each School has its own character and focused role paths."/><div className="mt-14 grid gap-5 lg:grid-cols-3">{schools.map((school,index)=>{const visual=schoolVisual[index];return <a href={`/schools/${school.slug}`} key={school.slug} className="card group flex min-h-[410px] flex-col p-7 transition duration-200 hover:-translate-y-1 hover:shadow-lift"><div className="flex items-center justify-between"><span className={`grid size-12 place-items-center rounded-xl ${visual.tone}`}><AcademyIcon name={visual.icon} className="size-6"/></span><span className="rounded-full border bg-paper px-3 py-1.5 text-[10px] font-bold text-zinc-500">{visual.stat}</span></div><p className="eyebrow mt-12">School {school.index}</p><h3 className="mt-5 font-display text-[46px] leading-[.95] tracking-tight">{school.name}</h3><p className="mt-5 text-sm leading-6 text-zinc-600">{school.purpose}</p><span className="mt-auto flex items-center gap-2 border-t pt-5 text-xs font-bold">Explore Tracks <ArrowRightIcon className="size-4 transition group-hover:translate-x-1"/></span></a>})}</div></div></section>

    <section className="section shell"><SectionHeading number="02" label="Featured roles" title={<>See who you<br/>could become.</>} copy="A few of our most popular role paths. Begin at a School to explore every option."/><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{featured.map(track=><TrackCard track={track} key={track.slug}/>)}</div><div className="mt-10 text-center"><a className="button-secondary" href="/schools">Explore Tracks <ArrowRightIcon className="size-4"/></a></div></section>

    <section className="section bg-night text-white"><div className="shell"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow !text-zinc-500">Proof, not promises</p><h2 className="display mt-7 text-5xl sm:text-7xl">Graduate with<br/>work to show.</h2><p className="mt-6 max-w-md text-base leading-7 text-zinc-400">Projects and certification are built into each role—not sold as separate extras.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[#1A2230] p-7"><span className="grid size-11 place-items-center rounded-xl bg-blue-300/10 text-blue-300"><AcademyIcon name="project" className="size-6"/></span><p className="eyebrow mt-10 !text-zinc-500">Portfolio</p><h3 className="mt-3 font-display text-4xl">Real projects</h3><p className="mt-4 text-sm leading-6 text-zinc-400">Reviewed work built around realistic constraints.</p></div><div className="rounded-2xl bg-[#F1EDE4] p-7 text-ink"><span className="grid size-11 place-items-center rounded-xl bg-white text-warning"><AcademyIcon name="certification" className="size-6"/></span><p className="eyebrow mt-10">Credential</p><h3 className="mt-3 font-display text-4xl">Verified outcome</h3><p className="mt-4 text-sm leading-6 text-zinc-600">A role certificate backed by completed work.</p></div></div></div><div className="mt-16 grid grid-cols-2 gap-px overflow-hidden rounded-2xl bg-zinc-700 sm:grid-cols-4">{[['14','career roles'],['70+','guided projects'],['4.9','learner rating'],['3','focused Schools']].map(([stat,label])=><div className="bg-night p-7 text-center" key={label}><strong className="font-display text-4xl font-normal">{stat}</strong><span className="mt-2 block text-[10px] font-bold uppercase tracking-wider text-zinc-500">{label}</span></div>)}</div></div></section>

    <section className="section bg-sand"><div className="shell grid gap-12 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><blockquote className="font-display text-5xl leading-[1.05] tracking-tight sm:text-7xl">“The roadmap replaced uncertainty with <em className="font-normal text-cobalt">momentum.</em> Every week connected to the role.”</blockquote><div className="rounded-2xl border border-stone-300 bg-white/70 p-6"><div className="flex items-center gap-4"><span className="grid size-12 place-items-center rounded-full bg-stone-300 text-xs font-bold">AK</span><div><strong className="block text-sm">Aakriti Karki</strong><span className="text-xs text-zinc-600">AI Automation Specialist</span></div></div><div className="mt-6 flex gap-6 border-t pt-5 text-[10px] font-bold text-zinc-500"><span>CAREER SWITCH</span><span>5 MONTHS</span></div></div></div></section>

    <section className="section shell"><div className="relative overflow-hidden rounded-[28px] bg-cobalt p-9 text-white sm:p-14 lg:p-20"><div className="absolute -right-20 -top-24 size-80 rounded-full border-[60px] border-white/5"/><div className="relative flex flex-col justify-between gap-12 lg:flex-row lg:items-end"><div><p className="eyebrow !text-blue-200">Your next step</p><h2 className="display mt-7 text-5xl sm:text-7xl">Find the role<br/>that fits.</h2><p className="mt-6 max-w-lg text-base leading-7 text-blue-100">Compare the three Schools and explore the careers inside each one.</p></div><a className="button-secondary min-w-56" href="/schools">Explore Tracks <ArrowRightIcon className="size-4"/></a></div></div></section>
  </main>;
}
