import SectionHeading from '@/components/SectionHeading';
import { schools, tracks } from '@/lib/academy';

const featured = ['ai-full-stack-engineer','ai-automation-engineer','ai-career-accelerator'].map(slug => tracks.find(track => track.slug === slug));

export default function Home() {
  return <main>
    <section className="shell relative flex min-h-[700px] flex-col items-center justify-center overflow-hidden py-28 text-center">
      <div className="absolute inset-0 -z-10 bg-[linear-gradient(#e3e3de_1px,transparent_1px),linear-gradient(90deg,#e3e3de_1px,transparent_1px)] bg-[size:88px_88px] [mask-image:radial-gradient(circle_at_center,black,transparent_72%)]" />
      <p className="eyebrow flex items-center gap-3"><span className="size-2 rounded-full bg-cobalt"/>A modern career university</p>
      <h1 className="mt-9 font-display text-[58px] font-normal leading-[.88] tracking-[-.055em] sm:text-[90px] lg:text-[124px]">Choose a career.<br/><em className="font-normal text-cobalt">We’ll map the path.</em></h1>
      <p className="mt-9 max-w-2xl text-lg leading-8 text-zinc-600 sm:text-xl">Career-first learning for the AI era. One clear journey from foundational skills to real projects, certification, and work.</p>
      <div className="mt-10"><a className="button-primary" href="/schools">Explore Tracks →</a></div>
    </section>

    <section className="section shell">
      <div className="grid gap-12 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><div><p className="eyebrow">Why career-first</p><h2 className="display mt-7">Tools change.<br/>Direction matters.</h2></div><div className="space-y-5 text-base leading-8 text-zinc-600"><p className="font-semibold text-ink">A random collection of courses does not make a career.</p><p>We start with the role, then connect every skill, project, and credential needed to reach it.</p><div className="flex items-center gap-3 pt-3 text-[11px] font-bold uppercase tracking-wider"><span>School</span><span className="text-cobalt">→</span><span>Track</span><span className="text-cobalt">→</span><span>Skills</span><span className="text-cobalt">→</span><span>Career</span></div></div></div>
    </section>

    <section className="section border-y bg-white" id="schools"><div className="shell"><SectionHeading number="01" label="The academy" title={<>Three schools.<br/>Built around outcomes.</>} copy="Choose the field that fits your ambition. Each school contains focused role-based paths with a defined destination."/><div className="mt-16 grid gap-5 lg:grid-cols-3">{schools.map((school,index) => <a href={`/schools/${school.slug}`} key={school.slug} className={`group flex min-h-[430px] flex-col rounded-2xl border p-8 transition hover:-translate-y-1 hover:shadow-card ${index === 0 ? 'border-cobalt bg-cobalt text-white' : 'bg-paper'}`}><span className={`grid size-12 place-items-center rounded-xl border text-xl ${index === 0 ? 'border-white/30' : ''}`}>{school.icon}</span><p className={`eyebrow mt-14 ${index === 0 ? '!text-blue-200' : ''}`}>School {school.index}</p><h3 className="mt-5 font-display text-5xl leading-[.95] tracking-tight">{school.name}</h3><p className={`mt-6 text-sm leading-7 ${index === 0 ? 'text-blue-100' : 'text-zinc-600'}`}>{school.purpose}</p><div className={`mt-auto flex items-center justify-between border-t pt-5 text-[10px] font-bold uppercase tracking-wider ${index === 0 ? 'border-white/30' : ''}`}><span>{school.tracks.length} featured tracks</span><span className="grid size-9 place-items-center rounded-full border">↗</span></div></a>)}</div><div className="mt-10 text-center"><a className="button-secondary" href="/schools">Compare all schools →</a></div></div></section>

    <section className="section bg-night text-white"><div className="shell"><SectionHeading light number="02" label="Featured roles" title={<>Start with the role<br/>you want to become.</>} copy="Each role has a complete, structured journey—not a bundle of unrelated courses."/><div className="mt-16 border-t border-zinc-700">{featured.map((track,index) => <a href={`/roles/${track.slug}`} key={track.slug} className="group grid gap-6 border-b border-zinc-700 py-10 sm:grid-cols-[50px_1fr] lg:grid-cols-[50px_1fr_260px] lg:items-center"><span className="font-display text-xl text-zinc-600">0{index+1}</span><div><p className="eyebrow !text-blue-300">{schools.find(s=>s.slug===track.school).shortName}</p><h3 className="mt-4 font-display text-4xl sm:text-5xl">{track.name}</h3><p className="mt-3 text-sm text-zinc-400">{track.summary}</p></div><div className="border-zinc-700 pt-5 text-xs text-zinc-400 lg:border-l lg:py-5 lg:pl-8"><p>{track.duration} · {track.difficulty}</p><p className="mt-4 font-bold text-blue-300">View role roadmap →</p></div></a>)}</div><div className="mt-10 text-center"><a className="button-secondary" href="/schools">Explore Tracks →</a></div></div></section>

    <section className="section shell"><SectionHeading number="03" label="Graduate with proof" title={<>Learn the skills.<br/>Build the evidence.</>} copy="Every role journey concludes with reviewed portfolio work and a verifiable certification tied to the career outcome."/><div className="mt-16 grid gap-5 lg:grid-cols-2"><div className="card p-8 sm:p-12"><p className="eyebrow">Portfolio projects</p><div className="mt-10 rounded-xl bg-night p-8 text-white"><span className="text-[10px] font-bold text-blue-300">CAPSTONE</span><h3 className="mt-16 font-display text-4xl">Build something<br/>worth showing.</h3><p className="mt-5 max-w-md text-sm leading-6 text-zinc-400">Solve a real problem, document your decisions, and present working evidence.</p></div></div><div className="card p-8 sm:p-12"><p className="eyebrow">Verified certification</p><div className="mt-10 flex min-h-[260px] items-center justify-center rounded-xl border bg-blue-50"><div className="text-center"><span className="mx-auto grid size-24 place-items-center rounded-full border border-cobalt font-display text-5xl italic text-cobalt">T</span><h3 className="mt-6 font-display text-3xl">Role Certificate</h3><p className="mt-2 text-xs text-zinc-500">Shareable · Verifiable · Earned</p></div></div></div></div></section>

    <section className="section bg-[#e9e5dc]"><div className="shell"><p className="eyebrow">Student outcome</p><blockquote className="mt-12 max-w-6xl font-display text-5xl leading-[1.06] tracking-tight sm:text-7xl lg:text-[82px]">“I stopped wondering what to learn next. The roadmap made every week feel connected to <em className="font-normal text-cobalt">the role I wanted.</em>”</blockquote><div className="mt-12 flex items-center gap-4"><span className="grid size-12 place-items-center rounded-full bg-stone-300 text-xs font-bold">AK</span><div><strong className="block text-sm">Aakriti Karki</strong><span className="text-xs text-zinc-600">AI Automation Specialist · Career switch in 5 months</span></div></div><div className="mt-20 flex flex-wrap items-center justify-between gap-8 border-t border-stone-400/50 pt-9 text-zinc-600"><span className="eyebrow">Graduates are building at</span>{['Fusemachines','Leapfrog','Deerhold','Cotiviti','Naamche'].map(x=><strong key={x}>{x}</strong>)}</div></div></section>

    <section className="section shell"><div className="flex flex-col justify-between gap-12 rounded-3xl bg-cobalt p-9 text-white sm:p-14 lg:flex-row lg:items-end lg:p-20"><div><p className="eyebrow !text-blue-200">Find your direction</p><h2 className="display mt-7 text-5xl sm:text-7xl">Your career path<br/>starts with a School.</h2><p className="mt-6 max-w-lg leading-7 text-blue-100">Compare the three fields, see the roles inside each one, and choose with confidence.</p></div><a className="button-secondary min-w-60" href="/schools">Explore Tracks →</a></div></section>
  </main>;
}
